import { useState } from 'react';
import { Alert, Avatar, Box, Button, Chip, Paper, Snackbar, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';

const rows = [['20 May 14:22', 'RM', 'Rohan Mehta', 'APPROVED CORRECTION', 'ABC-...-11', 'Implant Name updated'], ['20 May 12:03', 'PS', 'Priya Sharma', 'ACKNOWLEDGED GUIDE', 'ABC v2.3', 'Read & understood'], ['20 May 09:41', 'SA', 'System Admin', 'CREATED USER', 'EMP-1160', 'Nikhil Verma / Indexer'], ['19 May 18:00', 'SY', 'System', 'AUTO-LOCKED ENTRIES', 'ABC Medical', '142 entries locked'], ['19 May 10:15', 'MN', 'Meera Nair', 'UPLOADED GUIDE', 'ABC v2.3', 'Notified 50 users']];

export default function AuditLog() {
	const [notice, setNotice] = useState(false);
	return <Box sx={{ maxWidth: 1100 }}><Typography sx={{ color: '#667085', fontSize: 12 }}>ProdTrack · Administrator</Typography><Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 2, mt: .7, mb: 2, '@media (max-width: 600px)': { flexDirection: 'column' } }}><Box><Typography sx={{ fontSize: 24, fontWeight: 800 }}>Audit log</Typography><Typography sx={{ color: '#667085', fontSize: 13, mt: .4 }}>User activity, change history and login events for compliance.</Typography></Box><Button variant="contained" onClick={() => setNotice(true)}>Export</Button></Box><Box sx={{ display: 'flex', gap: 3, borderBottom: '1px solid #dbe3ec', mb: 2, px: 1.5 }}><Button sx={{ borderRadius: 0, borderBottom: '2px solid #3478ed', color: '#3478ed', minWidth: 0 }}>Activity</Button><Button sx={{ color: '#526581' }}>Change history</Button><Button sx={{ color: '#526581' }}>Login events</Button></Box><Paper elevation={0} sx={{ border: '1px solid #dbe3ec', borderRadius: 1.5, overflow: 'auto', boxShadow: '0 2px 6px rgba(16,35,61,.08)' }}><Table size="small" sx={{ minWidth: 850 }}><TableHead><TableRow sx={{ bgcolor: '#f8fafc' }}>{['TIMESTAMP', 'USER', 'ACTION', 'ENTITY', 'DETAIL'].map(header => <TableCell key={header} sx={{ color: '#526581', fontSize: 11, fontWeight: 800, py: 1.4 }}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map(([time, initials, name, action, entity, detail]) => <TableRow key={`${time}-${name}`} hover><TableCell sx={{ color: '#526581', fontSize: 13 }}>{time}</TableCell><TableCell><Box sx={{ display: 'flex', alignItems: 'center', gap: 1, fontSize: 13 }}><Avatar sx={{ width: 27, height: 27, bgcolor: '#5b5ce2', fontSize: 11, fontWeight: 700 }}>{initials}</Avatar>{name}</Box></TableCell><TableCell><Chip label={action} size="small" sx={{ color: '#2458c7', bgcolor: '#eaf1ff', border: '1px solid #bcd2ff', fontSize: 10, fontWeight: 800 }} /></TableCell><TableCell sx={{ fontSize: 13, fontWeight: 600 }}>{entity}</TableCell><TableCell sx={{ color: '#667085', fontSize: 13 }}>{detail}</TableCell></TableRow>)}</TableBody></Table></Paper><Snackbar open={notice} autoHideDuration={2500} onClose={() => setNotice(false)} anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}><Alert severity="success" variant="filled" onClose={() => setNotice(false)}>Audit log exported successfully</Alert></Snackbar></Box>;
}
